"""typo at completed_at column

Revision ID: 3d5569a60bb8
Revises: 2034d38d6cb5
Create Date: 2024-11-01 14:35:12.110722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d5569a60bb8'
down_revision = '2034d38d6cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('complete_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
